version: "3"
services:
  mysql8.0:
    image: mysql:8.0
    container_name: mysql8.0
    ports:
      - 3380:3306
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    volumes:
      - ./conf.d:/etc/mysql/conf.d:ro
      - ./logs:/var/log/mysql:rw
      - ./db/mysql:/var/lib/mysql
